export const recommendations: string[] = [
  'Mantén una hidratación adecuada durante tus sesiones de entrenamiento.',
  'Prioriza el calentamiento para evitar lesiones durante tu rutina.',
  'Incluye ejercicios de estiramiento al finalizar para mejorar la flexibilidad.',
  'Usa ropa cómoda y adecuada para facilitar el movimiento al ejercitarte.',
  'Establece metas realistas y aumenta la intensidad de tu entrenamiento gradualmente.',
  'No te saltes las comidas antes de entrenar para mantener tus niveles de energía.',
  'Incluye tanto ejercicios cardiovasculares como de fuerza en tu rutina.',
  'Descansa lo suficiente entre series para permitir la recuperación muscular.',
  'Varía tus rutinas para trabajar diferentes grupos musculares.',
  'Escucha a tu cuerpo y reduce la intensidad si sientes dolor o molestia.',
  'Mantén una postura adecuada para maximizar la efectividad y evitar lesiones.',
  'Contrata a un entrenador personal si necesitas orientación o motivación extra.',
  'Evita el sobreentrenamiento dando a tu cuerpo tiempo para recuperarse.',
  'Balancea tu dieta con una buena proporción de proteínas, carbohidratos y grasas.',
  'Establece un horario de entrenamiento regular para desarrollar una rutina sólida.',
  'Registra tu progreso para mantenerte motivado y observar tus mejoras.',
  'No olvides incluir días de descanso en tu programa de entrenamiento semanal.',
  'Utiliza la música para mantenerte energizado y concentrado durante el ejercicio.',
  'Asegúrate de consumir proteínas después de entrenar para ayudar a la recuperación muscular.',
  'No descuides la importancia de una buena noche de sueño para la recuperación.',
  'Incorpora ejercicios de equilibrio y coordinación para una rutina más completa.',
  'Mantén una actitud positiva, incluso en los días en que entrenar es un desafío.',
  'Prueba clases grupales para diversificar tu entrenamiento y conocer gente nueva.',
  'Mantén tu estación de entrenamiento limpia y ordenada por respeto a los demás.',
  'No compares tu progreso con el de los demás; cada persona es única.',
  'Aprende y practica la técnica correcta antes de aumentar el peso o la intensidad.',
  'Recuerda que la calidad del movimiento es más importante que la cantidad de peso.',
  'Utiliza un cinturón de levantamiento para soporte adicional en ejercicios pesados.',
  'Siempre coloca los pesos en su lugar después de usarlos para mantener el orden.',
  'Evita el consumo excesivo de bebidas energéticas o suplementos sin asesoría profesional.',
  'Realiza un chequeo médico antes de empezar cualquier programa de entrenamiento nuevo.',
  'Incluye alimentos ricos en fibras en tu dieta para mejorar la digestión.',
  'Consume suficientes antioxidantes en tu dieta para combatir el estrés oxidativo.',
  'Experimenta con diferentes horarios de entrenamiento para encontrar el que mejor se adapte a ti.',
  'No ignores el dolor; si persiste, consulta a un profesional de la salud.',
  'No te excedas con el cardio si tu objetivo principal es ganar masa muscular.',
  'Busca un compañero de entrenamiento para ayudarte a mantenerte responsable.',
  'Siempre hidrátate bien, no solo durante, sino antes y después del ejercicio.',
  'Invierte en un buen par de zapatillas deportivas que ofrezcan soporte y comodidad.',
  'Realiza entrenamientos de alta intensidad para mejorar la resistencia y quemar grasa.',
  'No te saltes las comidas post-entrenamiento; son clave para tu recuperación.',
  'Incorpora ejercicios funcionales que imiten movimientos cotidianos.',
  'Evita distraerte con el teléfono para mantener la concentración en tu entrenamiento.',
  'Si te sientes enfermo o fatigado, es mejor descansar y recuperarte completamente.',
  'La constancia es clave; el progreso se ve con el tiempo, no de la noche a la mañana.',
  'Intenta hacer ejercicios compuestos para trabajar múltiples grupos musculares a la vez.',
  'La respiración adecuada es crucial; no contengas la respiración al ejercitarte.',
  'Mantén un diario de nutrición para asegurarte de que estás comiendo para tus objetivos.',
  'Agrega intervalos de velocidad a tu entrenamiento para mejorar la capacidad cardiovascular.',
  'Celebra tus logros, no importa qué tan pequeños sean, para mantener la motivación.',
  'Mantén una mentalidad de crecimiento; siempre hay espacio para mejorar y aprender.',
];